# Generated by Django 6.0.3 on 2026-04-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.SmallIntegerField(choices=[(1, 'Chevrolet'), (2, 'Fiat'), (3, 'Ford'), (4, 'Volkswagen'), (5, 'Toyota'), (6, 'Honda'), (7, 'Hyundai'), (8, 'Outra')])),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.SmallIntegerField(choices=[(1, 'Preto'), (2, 'Branco'), (3, 'Prata'), (4, 'Cinza'), (5, 'Vermelho'), (6, 'Azul'), (7, 'Outra')])),
                ('combustivel', models.SmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Etanol'), (3, 'Flex'), (4, 'Diesel'), (5, 'GNV'), (6, 'Elétrico/Híbrido')])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='veiculo/fotos')),
            ],
        ),
    ]
